module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        yellow: "#FEFF05",
        green: "#01A47B",
        "green-light": "#05D5A1",
        "body": "#1b527b",
      },
      fontFamily: {
        scratchy: ['Scratchy', 'serif'],
        jangkuy: ['Jangkuy', 'serif'],
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        TRITON: {
          primary: '#541FF3',
          "primary-focus": "#541FF3",
          "primary-content": "#181830",
          secondary: "#3DB489",
          "secondary-focus": "#3DB489",
          "secondary-content": "#ffffff",
          accent: "#181830",
          "accent-focus": "#111122",
          "accent-content": "#ffffff",
          neutral: "#181830",
          "neutral-focus": "#111122",
          "neutral-content": "#ffffff",
          "base-100": "transparent",
          "base-200": "#ffffff",
          "base-300": "#A134FE",
          "base-content": "#000000",
          info: "#2094f3",
          success: "#009485",
          warning: "#ff9900",
          error: "#ff5724",
          "--border-color": "var(--b3)",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": ".2s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--navbar-padding": ".5rem",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
      },
    ],
  },
};
